<?php
/**
 * Central storage location for every KarMCP sandbox artifact — PHP snippets,
 * generated widgets, custom blocks, and PHP theme templates.
 *
 * Historically these were scattered inside `wp-content/uploads/karmcp-widgets/`.
 * They now live in a single dedicated `wp-content/karmcp-sandbox/` directory
 * (subdirs: snippets/ widgets/ blocks/ theme-php/). Every store resolves its
 * paths through this one class so the location is defined in a single place.
 *
 * Manifests store RELATIVE paths plus content hashes, and the loaders resolve
 * each file against the current base — so the directory can be relocated
 * without rebuilding a single manifest (every hash still matches).
 *
 * @package KarMCP
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class KarMCP_Sandbox_Paths {
	/** Default folder name, directly under wp-content. */
	const DEFAULT_FOLDER = 'karmcp-sandbox';
	/** Previous location: this folder under the uploads basedir. */
	const LEGACY_FOLDER = 'karmcp-widgets';
	/** Option flag recording that the one-time relocation has run. */
	const MIGRATED_OPTION = 'karmcp_sandbox_location';

	/**
	 * Folder name under wp-content. Filterable, sanitized to a single safe path
	 * segment.
	 *
	 * @return string
	 */
	public static function folder(): string {
		$f = (string) apply_filters( 'karmcp_sandbox_folder', self::DEFAULT_FOLDER );
		$f = (string) preg_replace( '/[^A-Za-z0-9\-_]/', '', $f );
		return '' !== $f ? $f : self::DEFAULT_FOLDER;
	}

	/**
	 * Absolute base directory, e.g. `/…/wp-content/karmcp-sandbox` (no trailing slash).
	 *
	 * @return string
	 */
	public static function base_dir(): string {
		$dir = rtrim( WP_CONTENT_DIR, '/\\' ) . '/' . self::folder();
		/**
		 * Filter the absolute sandbox base directory. Pair with
		 * `karmcp_sandbox_url` to keep the served URL consistent when
		 * relocating outside wp-content.
		 *
		 * @param string $dir Absolute directory path (no trailing slash).
		 */
		return rtrim( (string) apply_filters( 'karmcp_sandbox_dir', $dir ), '/\\' );
	}

	/**
	 * Public base URL, e.g. `https://site/wp-content/karmcp-sandbox` (no trailing slash).
	 *
	 * @return string
	 */
	public static function base_url(): string {
		$url = rtrim( content_url( self::folder() ), '/' );
		/**
		 * Filter the public sandbox base URL. Pair with `karmcp_sandbox_dir`
		 * so a relocated directory is still served from the right URL.
		 *
		 * @param string $url Base URL (no trailing slash).
		 */
		return rtrim( (string) apply_filters( 'karmcp_sandbox_url', $url ), '/' );
	}

	/**
	 * ABSPATH-relative base path, e.g. `wp-content/karmcp-sandbox` — used by the
	 * malware scanner to exclude the plugin's own sandboxed PHP.
	 *
	 * @return string
	 */
	public static function relative_base(): string {
		$base = str_replace( '\\', '/', self::base_dir() );
		$root = str_replace( '\\', '/', trailingslashit( ABSPATH ) );
		if ( 0 === strpos( $base, $root ) ) {
			return substr( $base, strlen( $root ) );
		}
		return 'wp-content/' . self::folder();
	}

	/**
	 * The old scattered location (uploads/karmcp-widgets), for migration.
	 *
	 * @return string
	 */
	public static function legacy_dir(): string {
		$u = wp_upload_dir();
		return trailingslashit( $u['basedir'] ) . self::LEGACY_FOLDER;
	}

	/**
	 * Write the base web-access guards: an index.php (silence) and an .htaccess
	 * that blocks direct PHP execution while still allowing css/js assets to be
	 * served. Idempotent.
	 *
	 * @return void
	 */
	public static function harden(): void {
		$base = self::base_dir();
		wp_mkdir_p( $base );
		self::write( $base . '/index.php', "<?php\n// Silence is golden.\n" );
		self::write(
			$base . '/.htaccess',
			"# Generated by MCP Tools for Elementor, block direct PHP; allow css/js assets.\n<FilesMatch \"\\.php$\">\n<IfModule mod_authz_core.c>\nRequire all denied\n</IfModule>\n<IfModule !mod_authz_core.c>\ndeny from all\n</IfModule>\n</FilesMatch>\n"
		);
	}

	/**
	 * Ensure a subdirectory exists and carries a silence index.php.
	 *
	 * @param string $dir Absolute directory path.
	 * @return void
	 */
	public static function guard_subdir( string $dir ): void {
		wp_mkdir_p( $dir );
		self::write( $dir . '/index.php', "<?php\n// Silence is golden.\n" );
	}

	/**
	 * One-time relocation of the legacy uploads/karmcp-widgets tree to the new
	 * wp-content/karmcp-sandbox base. Runs during bootstrap (plugins_loaded),
	 * before the artifact loaders fire on `init`. Manifests carry relative
	 * paths + content hashes, so no rebuild is required — the loaders resolve
	 * against the new base and every hash still verifies. Short-circuits after
	 * the first successful run.
	 *
	 * @return void
	 */
	public static function maybe_migrate(): void {
		if ( self::folder() === (string) get_option( self::MIGRATED_OPTION, '' ) ) {
			return;
		}
		$old = self::legacy_dir();
		$new = self::base_dir();
		if ( is_dir( $old ) && ! is_dir( $new ) ) {
			wp_mkdir_p( dirname( $new ) );
			// phpcs:ignore WordPress.WP.AlternativeFunctions.rename_rename
			if ( ! @rename( $old, $new ) ) {
				// Cross-device fallback: copy the tree, then remove the old copy
				// only if every file copied cleanly.
				if ( self::copy_tree( $old, $new ) && is_dir( $new ) ) {
					self::rmdir_tree( $old );
				}
			}
		}
		if ( is_dir( $new ) ) {
			self::harden();
		}
		update_option( self::MIGRATED_OPTION, self::folder(), true );
	}

	/**
	 * @param string $path     Absolute file path.
	 * @param string $contents File contents (skips the write if unchanged).
	 * @return void
	 */
	private static function write( string $path, string $contents ): void {
		if ( is_file( $path ) ) {
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
			if ( (string) @file_get_contents( $path ) === $contents ) {
				return;
			}
		}
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
		@file_put_contents( $path, $contents );
	}

	/**
	 * @param string $src Source dir.
	 * @param string $dst Destination dir.
	 * @return bool True only if every entry copied.
	 */
	private static function copy_tree( string $src, string $dst ): bool {
		if ( ! is_dir( $src ) || ! wp_mkdir_p( $dst ) ) {
			return false;
		}
		$items = scandir( $src );
		if ( false === $items ) {
			return false;
		}
		$ok = true;
		foreach ( $items as $i ) {
			if ( '.' === $i || '..' === $i ) {
				continue;
			}
			$s = $src . '/' . $i;
			$d = $dst . '/' . $i;
			if ( is_dir( $s ) ) {
				$ok = self::copy_tree( $s, $d ) && $ok;
			} else {
				// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_copy
				$ok = ( false !== @copy( $s, $d ) ) && $ok;
			}
		}
		return $ok;
	}

	/**
	 * @param string $dir Directory to remove recursively.
	 * @return void
	 */
	private static function rmdir_tree( string $dir ): void {
		if ( ! is_dir( $dir ) ) {
			return;
		}
		$items = scandir( $dir );
		if ( false === $items ) {
			return;
		}
		foreach ( $items as $i ) {
			if ( '.' === $i || '..' === $i ) {
				continue;
			}
			$p = $dir . '/' . $i;
			// phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink
			is_dir( $p ) ? self::rmdir_tree( $p ) : @unlink( $p );
		}
		// phpcs:ignore WordPress.WP.AlternativeFunctions.rmdir_rmdir
		@rmdir( $dir );
	}
}
