<?php
/**
 * Validates widget settings against Elementor control schemas.
 *
 * @package KarMCP
 * @since   1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Validates widget settings against their control definitions.
 *
 * @since 1.0.0
 */
class KarMCP_Settings_Validator {

	/**
	 * The schema generator instance.
	 *
	 * @var KarMCP_Schema_Generator
	 */
	private $schema_generator;

	/**
	 * Constructor.
	 *
	 * @since 1.0.0
	 *
	 * @param KarMCP_Schema_Generator $schema_generator The schema generator.
	 */
	public function __construct( KarMCP_Schema_Generator $schema_generator ) {
		$this->schema_generator = $schema_generator;
	}

	/**
	 * Responsive breakpoint suffixes generated by Elementor's add_responsive_control().
	 *
	 * @var string[]
	 */
	private static $responsive_suffixes = array(
		'_mobile',
		'_tablet',
		'_widescreen',
		'_laptop',
		'_mobile_extra',
		'_tablet_extra',
	);

	/**
	 * Common advanced control keys valid for ALL widget types.
	 * From Elementor's Widget_Common_Base (common-base.php).
	 *
	 * @var string[]
	 */
	private static $common_advanced_keys = array(
		// Positioning.
		'_element_width', '_element_custom_width', '_element_vertical_align',
		'_position', '_offset_orientation_h', '_offset_x', '_offset_x_end',
		'_offset_orientation_v', '_offset_y', '_offset_y_end',
		'_z_index', '_element_id', '_css_classes',
		// Spacing.
		'_margin', '_padding',
		// Background (normal + hover).
		'_background_background', '_background_color', '_background_image',
		'_background_position', '_background_attachment', '_background_repeat',
		'_background_size', '_background_bg_width',
		'_background_hover_background', '_background_hover_color',
		'_background_hover_transition',
		// Border (normal + hover).
		'_border_border', '_border_width', '_border_color',
		'_border_radius', '_border_hover_border', '_border_hover_width',
		'_border_hover_color', '_border_radius_hover',
		'_border_hover_transition',
		// Box shadow (normal + hover).
		'_box_shadow_box_shadow_type', '_box_shadow_box_shadow',
		'_box_shadow_hover_box_shadow_type', '_box_shadow_hover_box_shadow',
		// Mask.
		'_mask_switch', '_mask_shape', '_mask_image',
		'_mask_size', '_mask_size_scale',
		'_mask_position', '_mask_position_x', '_mask_position_y',
		'_mask_repeat',
		// Animation.
		'_animation', 'animation_duration', '_animation_delay',
		// Flex item.
		'_flex_align_self', '_flex_order', '_flex_order_custom',
		'_flex_size', '_flex_grow', '_flex_shrink',
		// Grid item.
		'_grid_column', '_grid_column_custom', '_grid_row', '_grid_row_custom',
		// Responsive visibility.
		'hide_desktop', 'hide_tablet', 'hide_mobile',
		// Motion effects (Pro) — actual Elementor schema keys use motion_fx_ prefix.
		'motion_fx_motion_fx_scrolling', 'motion_fx_motion_fx_mouse',
		'motion_fx_devices', 'motion_fx_range',
		'motion_fx_translateY_effect', 'motion_fx_translateY_direction',
		'motion_fx_translateY_speed', 'motion_fx_translateY_affectedRange',
		'motion_fx_translateX_effect', 'motion_fx_translateX_direction',
		'motion_fx_translateX_speed', 'motion_fx_translateX_affectedRange',
		'motion_fx_opacity_effect', 'motion_fx_opacity_direction',
		'motion_fx_opacity_level', 'motion_fx_opacity_range',
		'motion_fx_blur_effect', 'motion_fx_blur_direction',
		'motion_fx_blur_level', 'motion_fx_blur_range',
		'motion_fx_rotateZ_effect', 'motion_fx_rotateZ_direction',
		'motion_fx_rotateZ_speed', 'motion_fx_rotateZ_affectedRange',
		'motion_fx_scale_effect', 'motion_fx_scale_direction',
		'motion_fx_scale_speed', 'motion_fx_scale_range',
		'motion_fx_tilt_effect', 'motion_fx_tilt_direction', 'motion_fx_tilt_speed',
		'motion_fx_mouseTrack_effect', 'motion_fx_mouseTrack_direction', 'motion_fx_mouseTrack_speed',
		'motion_fx_transform_origin_x', 'motion_fx_transform_origin_y',
		'motion_fx_transform_x_anchor_point', 'motion_fx_transform_y_anchor_point',
		'handle_motion_fx_asset_loading',
		// CSS Transform controls.
		'_transform_rotate_popover', '_transform_rotateZ_effect',
		'_transform_rotate_3d', '_transform_rotateX_effect', '_transform_rotateY_effect',
		'_transform_translate_popover', '_transform_translateX_effect', '_transform_translateY_effect',
		'_transform_scale_popover', '_transform_scale_effect',
		'_transform_scaleX_effect', '_transform_scaleY_effect',
		'_transform_rotate_popover_hover', '_transform_rotateZ_effect_hover',
		'_transform_rotate_3d_hover', '_transform_rotateX_effect_hover', '_transform_rotateY_effect_hover',
		'_transform_translate_popover_hover', '_transform_translateX_effect_hover', '_transform_translateY_effect_hover',
		'_transform_scale_popover_hover', '_transform_scale_effect_hover',
		'_transform_scaleX_effect_hover', '_transform_scaleY_effect_hover',
	);

	/**
	 * Validates settings for a widget type (non-fatal / advisory).
	 *
	 * IMPORTANT: this never hard-rejects a setting. Elementor's headless
	 * `get_widget_types($t)->get_controls()` — the source our schema is built
	 * from — systematically OMITS group controls (typography) and tabbed style
	 * controls (e.g. `title_color`) for every widget in a REST/CLI context, even
	 * though they are real controls registered in the widget's `register_controls()`
	 * (confirmed in Elementor core, e.g. heading.php's `title_color` + `typography`).
	 * Treating that incomplete list as an allow-list previously rejected valid
	 * styling and aborted the whole insert.
	 *
	 * Elementor itself is the real authority: it applies the controls it knows on
	 * render and ignores genuinely-unknown keys. So we pass settings through and
	 * only LOG keys we can't account for (diagnostics), never block.
	 *
	 * @since 1.0.0
	 * @since 2.2.0 Non-fatal: returns true for unrecognised keys (logs them under WP_DEBUG)
	 *              instead of returning a WP_Error.
	 *
	 * @param string $widget_type The widget type name.
	 * @param array  $settings    The settings to validate.
	 * @return true Always true; the method is advisory only.
	 */
	public function validate( string $widget_type, array $settings ) {
		$unknown = $this->unknown_keys( $widget_type, $settings );

		// Unknown keys are very often real controls the headless schema can't see
		// (typography, colours). Pass them through; log for diagnostics only.
		if ( ! empty( $unknown ) && defined( 'WP_DEBUG' ) && WP_DEBUG ) {
			error_log(
				sprintf(
					'[KarMCP] Passing through %1$d unrecognised setting(s) for widget "%2$s" (absent from the headless control schema): %3$s',
					count( $unknown ),
					$widget_type,
					implode( ', ', $unknown )
				)
			);
		}

		return true;
	}

	/**
	 * Whether this widget comes from something other than Elementor, in which
	 * case its introspected control list cannot be treated as the whole
	 * vocabulary.
	 *
	 * For Elementor's own widgets it can be: `get_full_controls()` flips
	 * Performance::use_style_controls while it reads, so the set comes back
	 * complete. A third-party addon is a different animal. Unlimited Elements is
	 * the case that proved it — its `ucaddon_*` widgets build controls from the
	 * addon's own definition, and keys demonstrably live on the page
	 * (`border_top_width` / `border_top_height` on `ucaddon_item_menu`, the top
	 * rule of a module card, visible on screen) are absent from the ~600
	 * controls introspection returns. Flagging those produced a warning that was
	 * wrong and a `did_you_mean` that was worse: `minimum_height` offered as the
	 * correction for `border_top_height`, pushing the caller to "fix" a name
	 * that already worked.
	 *
	 * The test is deliberately positive — it answers true only with the widget
	 * object in hand and a class outside Elementor's namespaces. Anywhere the
	 * question cannot be settled (Elementor absent, widget unregistered) it
	 * answers false and the existing reporting stands: silence is for evidence
	 * of a third-party widget, not for the absence of evidence.
	 *
	 * @since 1.25.1
	 *
	 * @param string $widget_type The widget type name.
	 * @return bool
	 */
	private function is_third_party_widget( string $widget_type ): bool {
		if ( ! class_exists( '\Elementor\Plugin' ) || ! isset( \Elementor\Plugin::$instance->widgets_manager ) ) {
			return false;
		}

		$manager = \Elementor\Plugin::$instance->widgets_manager;
		if ( ! is_object( $manager ) || ! method_exists( $manager, 'get_widget_types' ) ) {
			return false;
		}

		$widget = $manager->get_widget_types( $widget_type );
		if ( ! is_object( $widget ) ) {
			return false;
		}

		$class = get_class( $widget );

		return 0 !== strpos( $class, 'Elementor\\' ) && 0 !== strpos( $class, 'ElementorPro\\' );
	}

	/**
	 * The settings keys that match no control this widget is known to have.
	 *
	 * Same accounting `validate()` has always done, returned instead of only
	 * logged. A caller can then say so in its response, which is the difference
	 * between a typo costing a moment and costing a debugging session: writes
	 * accept any key, store it in `_elementor_data`, and answer `success`, so a
	 * misspelled control reads as applied everywhere except on the page.
	 *
	 * Advisory, and it has to stay advisory. The headless control list is
	 * incomplete (see validate()), dynamic tags and third-party addons add keys
	 * at runtime, so a name absent from it is suspicious, not wrong.
	 *
	 * @since 1.20.0
	 *
	 * @param string $widget_type The widget type name.
	 * @param array  $settings    The settings being written.
	 * @return string[] Unaccounted-for keys, in the order given.
	 */
	public function unknown_keys( string $widget_type, array $settings ): array {
		// A third-party widget's control list is not its whole vocabulary. See
		// is_third_party_widget().
		if ( $this->is_third_party_widget( $widget_type ) ) {
			return array();
		}

		$schema = $this->schema_generator->generate( $widget_type );

		// Can't introspect controls (unknown widget, Elementor unavailable, etc.):
		// claim nothing rather than flag everything.
		if ( is_wp_error( $schema ) ) {
			return array();
		}

		$valid_keys = array_keys( $schema['properties'] ?? array() );
		$unknown    = array();

		/*
		 * Deliberately WITHOUT is_group_control_subkey().
		 *
		 * That helper accepts any key sharing a prefix with a known control,
		 * and on this widget `button_` is a prefix of half the control set —
		 * so `button_padding`, `button_background_color` and even
		 * `button_pepito_inventado` all passed as valid. The check existed and
		 * caught nothing that mattered: the two names that motivated it both
		 * begin with `button_`.
		 *
		 * The helper was written when the schema was genuinely incomplete —
		 * Elementor's Optimized Control Loading strips style controls outside
		 * the editor. KarMCP_Schema_Generator::get_full_controls() has since
		 * fixed that at the source by flipping Performance::use_style_controls
		 * while it reads, so `properties` now carries the whole set: verified
		 * against Elementor 4.2.x, where the button schema contains
		 * `text_padding`, `typography_font_family` and
		 * `button_background_hover_color`, and does NOT contain `button_padding`
		 * (that one is the kit's) or `button_background_color`.
		 *
		 * With a complete list, exact matching is both possible and the point.
		 * Responsive variants still need their own check, because Elementor
		 * only registers a few of them explicitly.
		 *
		 * The helper stays for validate()'s logging, which is diagnostic and
		 * where a loose match costs nothing.
		 */
		foreach ( array_keys( $settings ) as $key ) {
			if ( in_array( $key, self::STRUCTURAL_KEYS, true )
				|| in_array( $key, $valid_keys, true )
				|| in_array( $key, self::$common_advanced_keys, true )
				|| $this->is_responsive_variant( $key, $valid_keys )
			) {
				continue;
			}
			$unknown[] = $key;
		}

		return $unknown;
	}

	/**
	 * Keys Elementor stores alongside the settings that are not controls.
	 *
	 * `__globals__` holds the bindings from a control to a global colour or
	 * font, and `__dynamic__` the dynamic-tag bindings. Both sit in the same
	 * settings array as the controls and neither will ever appear in a control
	 * list, so the exact-match check introduced in 1.20.1 reported `__globals__`
	 * on every write that used a global — which is the recommended way to
	 * theme a course, so the warning fired on correct work.
	 *
	 * @since 1.20.2
	 * @var string[]
	 */
	private const STRUCTURAL_KEYS = array( '__globals__', '__dynamic__' );

	/**
	 * Controls whose name is close to one that wasn't recognised.
	 *
	 * Both real cases this exists for were near-misses of a real control:
	 * `button_background_color` for `background_color`, and `button_padding` —
	 * the kit's name — for the widget's `text_padding`. Neither is a typo in
	 * the edit-distance sense, so matching is done on the trailing segments:
	 * `*_padding` finds `text_padding`, which spelling distance never would.
	 *
	 * @since 1.20.0
	 *
	 * @param string $widget_type The widget type name.
	 * @param string $key         The unrecognised key.
	 * @param int    $limit       Maximum suggestions.
	 * @return string[] Candidate control names, closest first.
	 */
	public function suggest_controls( string $widget_type, string $key, int $limit = 3 ): array {
		$schema = $this->schema_generator->generate( $widget_type );

		if ( is_wp_error( $schema ) ) {
			return array();
		}

		$candidates = array_keys( $schema['properties'] ?? array() );
		$scored     = array();

		foreach ( $candidates as $candidate ) {
			$score = 0;

			// Shared trailing segment: the signal that actually fires here.
			$key_tail       = strrchr( $key, '_' );
			$candidate_tail = strrchr( $candidate, '_' );
			if ( false !== $key_tail && $key_tail === $candidate_tail ) {
				$score += 100;
			}

			// One name containing the other: button_background_color →
			// background_color.
			if ( str_contains( $key, $candidate ) || str_contains( $candidate, $key ) ) {
				$score += 60;
			}

			// Spelling distance, for ordinary typos. Only close ones count.
			$distance = levenshtein( $key, $candidate );
			if ( $distance <= 3 ) {
				$score += ( 40 - ( $distance * 10 ) );
			}

			if ( $score > 0 ) {
				$scored[ $candidate ] = $score;
			}
		}

		arsort( $scored );

		return array_slice( array_keys( $scored ), 0, $limit );
	}

	/**
	 * Checks if a key is a responsive variant of a valid schema key or common key.
	 *
	 * @param string   $key        The settings key to check.
	 * @param string[] $valid_keys Valid keys from the widget schema.
	 * @return bool
	 */
	/**
	 * Checks if a key is a sub-field of a group control that has other keys in the schema.
	 *
	 * Group controls in Elementor use a shared prefix (e.g. 'text_stroke_', 'typography_',
	 * 'border_'). If any key with the same prefix exists in the schema, other sub-fields
	 * with that prefix are also valid.
	 *
	 * @param string   $key        The settings key to check.
	 * @param string[] $valid_keys Valid keys from the widget schema.
	 * @return bool
	 */
	private function is_group_control_subkey( string $key, array $valid_keys ): bool {
		// Try progressively shorter prefixes (split on '_').
		$parts = explode( '_', $key );
		// Need at least 2 parts for a group prefix (e.g. 'text_stroke' from 'text_stroke_stroke_width').
		for ( $i = 1, $len = count( $parts ) - 1; $i <= $len; $i++ ) {
			$prefix = implode( '_', array_slice( $parts, 0, $i ) ) . '_';
			foreach ( $valid_keys as $valid_key ) {
				if ( str_starts_with( $valid_key, $prefix ) && $valid_key !== $key ) {
					return true;
				}
			}
		}
		return false;
	}

	private function is_responsive_variant( string $key, array $valid_keys ): bool {
		foreach ( self::$responsive_suffixes as $suffix ) {
			if ( str_ends_with( $key, $suffix ) ) {
				$base_key = substr( $key, 0, -strlen( $suffix ) );
				if ( in_array( $base_key, $valid_keys, true ) ) {
					return true;
				}
				if ( in_array( $base_key, self::$common_advanced_keys, true ) ) {
					return true;
				}
			}
		}

		return false;
	}
}
